- name: Retrieve duplicacy latest release info
  ansible.builtin.uri:
    url: https://api.github.com/repos/gilbertchen/duplicacy/releases/latest
    return_content: true
  register: json_response

- name: Download x64 duplicacy binary
  when: ( 'linux_x64' in item.name ) and ( ansible_architecture == 'x86_64' )
  ansible.builtin.get_url:
    url: "{{ item.browser_download_url }}"
    dest: /usr/local/bin/duplicacy
    force: true
    mode: "0777"
    owner: root
    group: root
  loop: "{{ json_response.json.assets }}"
  loop_control:
    label: "{{ item.name }}"

- name: Download arm64 duplicacy binary
  when: ( 'linux_arm64' in item.name ) and ( ansible_architecture == 'aarch64' )
  ansible.builtin.get_url:
    url: "{{ item.browser_download_url }}"
    dest: /usr/local/bin/duplicacy
    force: true
    mode: "0777"
    owner: root
    group: root
  loop: "{{ json_response.json.assets }}"
  loop_control:
    label: "{{ item.name }}"
